version: '3.8'
services:
  mysql:
    image: arm64v8/mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stock
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - stock-analysis

volumes:
  mysql_data:
    driver: local

networks:
  stock-analysis:
    driver: bridge
