name: Database Migration
on:
  push:
    branches: [main]
jobs:
  check:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for OIDC token exchange
    outputs:
      skip_publish: ${{ steps.version_check.outputs.skip_publish }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@shindo-coding'

      - name: Version checking
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get version from package.json
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "Current package version: $PACKAGE_VERSION"

          # Check if package exists on GitHub Packages
          NPM_VERSION=$(npm view @shindo-coding/typed-prisma-package version --registry https://npm.pkg.github.com/ 2>/dev/null || echo "not_published")
          echo "Published version: $NPM_VERSION"

          # Skip if versions match
          if [ "$NPM_VERSION" = "$PACKAGE_VERSION" ]; then
            echo "Version $PACKAGE_VERSION is already published. Skipping."
            echo "SKIP_PUBLISH=true" >> $GITHUB_ENV
          else
            echo "Version $PACKAGE_VERSION is not published yet. Proceeding with publish."
            echo "SKIP_PUBLISH=false" >> $GITHUB_ENV
          fi

  create_release_id:
    needs: [check]
    if: needs.check.outputs.skip_publish != 'true'
    runs-on: self-hosted
    timeout-minutes: 20
    env:
      USE_RAND: ${{ inputs.use_rand && 'true' || 'false' }}
    # Map a step output to a job output
    outputs:
      tag: ${{ steps.create_id.outputs.DOCKER_TAG }}
    steps:
      - id: create_id
        run: |
          if [ "${USE_RAND}" == "true" ]
          then
            export DOCKER_TAG=$(openssl rand -hex 8)
          else
            export DOCKER_TAG=$(TZ="UTC" date +"%Y%m%d%H%M")
          fi
          echo "DOCKER_TAG=${DOCKER_TAG}" >> ${GITHUB_OUTPUT}

  package_docker:
    runs-on: self-hosted
    needs: [check, create_release_id]
    if: needs.check.outputs.skip_publish != 'true'
    env:
      CI_REGISTRY_IMAGE: shindo806/database-migrator
      PROJECT_NAME: database-migrator
      EXPOSE_PORT: 80
      SCALE_MIN: 1
      SCALE_MAX: 1
      DOCKER_TAG: ${{ needs.create_release_id.outputs.tag }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t $CI_REGISTRY_IMAGE:$DOCKER_TAG .
          docker push $CI_REGISTRY_IMAGE:$DOCKER_TAG

  deploy:
    runs-on: self-hosted
    needs: [check, package_docker]
    if: needs.check.outputs.skip_publish != 'true'

    env:
      CI_REGISTRY_IMAGE: shindo806/database-migrator
      PROJECT_NAME: database-migrator
      EXPOSE_PORT: 80
      MEM_MIN: 64Mi
      CPU_MIN: 100m
      MEM_MAX: 256Mi
      CPU_MAX: 500m
      SCALE_MIN: 1
      SCALE_MAX: 1
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Docker Tags
        id: fetch-latest-tag
        run: |
          # Fetch the JSON response from the Docker Hub
          response=$(curl -s "https://registry.hub.docker.com/v2/repositories/shindo806/${PROJECT_NAME}/tags")

          # Extract the tag names using jq
          tag=$(echo "$response" | jq -r '.results[0].name')

          # Print tags (for debugging purposes)
          echo "Tags:"
          echo "$tag"

          # Set the tags as an output
          echo "DOCKER_TAG=$tag" >> ${GITHUB_OUTPUT}

      - name: Substitute environment variables in template
        env:
          DOCKER_TAG: ${{ steps.fetch-latest-tag.outputs.DOCKER_TAG }}
        run: |
          envsubst < template.yaml > deployment.yaml
        shell: bash

      - name: Deploy to Kubernetes
        env:
          DOCKER_TAG: ${{ steps.fetch-latest-tag.outputs.DOCKER_TAG }}
        run: |
          cat deployment.yaml
          minikube kubectl -- apply -f deployment.yaml
          minikube kubectl -- rollout status deploy/$PROJECT_NAME
        shell: bash
