name: Prisma

on:
  push:
    branches:
      - master
  pull_request: {}

defaults:
  run:
    working-directory: prisma/

jobs:
  package:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Generate Client
        run: npx prisma generate

      - name: Pack the package
        run: npm pack

      # setup again with the github npm registry
      - name: Setup Node.js 22.x (GitHub npm registry)
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://npm.pkg.github.com/
          scope: "@sonlam806"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
